<?php

/**
 * @file
 * Functions to support theming in the SASS Starterkit subtheme.
 */

use Drupal\node\NodeInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_theme_registry_alter().
 */
function covid19_theme_registry_alter(&$theme_registry) {
  // covid19 path.
  $covid19_path = Drupal::service('theme_handler')->getTheme('covid19')->getPath();
  $theme_registry['entity_embed_container']['path'] = $covid19_path . '/templates/entity-embed';

  $pages = [
    'page__user__login' => 'page--user--login',
    'page__user__register' => 'page--user--register',
    'page__user__password' => 'page--user--password',
    'page__user__reset' => 'page--user--reset',
  ];

  foreach ($pages as $key => $template) {
    $theme_registry[$key]['path'] = $covid19_path . '/templates/betterlogin';
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function covid19_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    if (is_numeric($node)) {
      $node = Node::load($node);
    }
    if ($node instanceof NodeInterface) {
      array_splice($suggestions, 1, 0, 'page__' . $node->bundle());
    }
  }
}

/**
 * Implements hook_preprocess_html().
 */
function covid19_preprocess_html(&$variables) {

  // The path for covid19 theme in variables.
  $variables['covid19_path'] = drupal_get_path('theme', 'covid19');

  // Add information about the number of sidebars.
  if (theme_get_setting('bootstrap_barrio_navbar_position')) {
    $variables['navbar_position'] = theme_get_setting('bootstrap_barrio_navbar_position');
  }
}

/**
 * Implements hook_preprocess_page().
 */
function covid19_preprocess_page(&$variables) {
  // Add the pring logo.
  $variables['logo_print'] = \Drupal::request()->getBaseUrl() . '/' . drupal_get_path('theme', 'covid19') . '/logo-print.png';

  // Add the site name and slogan.
  $variables['site_name'] = \Drupal::config('system.site')->get('name');
  $variables['site_slogan'] = \Drupal::config('system.site')->get('slogan');
}

/**
 * Prepares variables for views grid templates.
 *
 * Default template: views-bootstrap-grid.html.twig.
 *
 * @param array $vars
 *   An associative array containing:
 *   - view: A ViewExecutable object.
 *   - rows: The raw row data.
 */
function covid19_preprocess_views_bootstrap_grid(array &$vars) {

  if (isset($vars['options']) && isset($vars['options']["col_xs"])) {
    $vars['options']["col_xs"] = str_replace("xs-", "", $vars['options']["col_xs"]);
  }

}

/**
 * Implements hook_form_alter().
 */
function covid19_form_alter(&$form, $form_state, $form_id) {

  if ($form_id == 'content_moderation_entity_moderation_form') {
    $form['#attributes']['class'][] = 'card card-body bg-light';
  }

  if ((preg_match('/^node_.*._layout_builder_form$/', $form_id)
    && isset($form['moderation_state']))) {
    $form['moderation_state']['#attributes']['class'][] = 'card card-body bg-light';
    $form['#attached']['library'][] = 'covid19/moderation-state';
  }
}
